version: '3.4'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - db.env

  bota.api.grpc:
    image: ${DOCKER_REGISTRY-}botaapigrpc
    restart: always
    build:
      context: .
      dockerfile: BOTA.API.gRPC/Dockerfile

  bota.api.openapi:
    image: ${DOCKER_REGISTRY-}botaapiopenapi
    restart: always
    build:
      context: .
      dockerfile: BOTA.API.OpenAPI/Dockerfile

  bota.api.rest.jsonapi:
    image: ${DOCKER_REGISTRY-}botaapirestjsonapi
    restart: always
    build:
      context: .
      dockerfile: BOTA.API.REST.JsonApi/Dockerfile
    
